# This is a basic workflow that is manually triggered

name: WordPress version

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "wpv"
  wpv:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout
      uses: actions/checkout@v2
    # Get WordPress version
    - name: Get WordPress version
      run: |
        export wpversion=$(git ls-remote --tags https://github.com/WordPress/WordPress.git | tail -n1 | awk -F'/' '{print $3}')
        echo $wpversion > index.html
        git pull
        git add .
        git commit -m "$wpversion, checked: $(date +'%F %T %Z')"
        git push origin main
